---
title: "Taux d'utilisation des capacités de production"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

Chargement des packages
```{r}
library(tidyverse)
library(eurostat)
library(lubridate)
library(janitor)
library(ggthemes)
library(mFilter)
```

# Utilisation des capacités de production

Importation des données 
```{r}
id <- "ei_bsin_q_r2"
cp <- get_eurostat(id)
cp_clean <- cp %>% 
  filter(s_adj == "SA", 
         geo == "PT",
         indic == "BS-ICU-PC") %>% 
  select(indic, TIME_PERIOD, values)
```

Graphique 
```{r}
cap_24_25 <- cp_clean %>%
  filter(TIME_PERIOD >= as.Date("2024-01-01"))

ggplot(cap_24_25, aes(x = TIME_PERIOD, y = values)) +
  geom_line(col = "steelblue", size = 1) +
  labs(
    title = "Taux d'utilisation des capacités — Portugal",
    subtitle = "2024–2025",
    x = "Date (trimestre)",
    y = "Capacité utilisée (%)"
  ) +
  theme_minimal()
```

Tableau
```{r}
print(cap_24_25)
write.csv2(cap_24_25, "capacite_prod.csv",
           row.names = FALSE, fileEncoding = "UTF-8")
```

