---
title: "Conjoncture 1"
author: "Antton Branger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Chargement des packages 
```{r, include=FALSE}
library(tidyverse)
```

Importation des données 
```{r}
chomage <- read.csv2("Chômage.csv")
commerce_ext <- read.csv2("Commerce ext.csv")
depense_pub <- read.csv2("Depense publique.csv")
fbcf <- read.csv2("FBCF.csv")
ipc <- read.csv2("IPC.csv")
pib <- read.csv2("PIB_annuel.csv")
```

Analyse des données 
```{r}
chomage <- chomage %>% 
  mutate(OBS_VALUE = as.numeric(OBS_VALUE)) %>% 
  select(-c(DATAFLOW, LAST.UPDATE, freq, geo, OBS_FLAG, CONF_STATUS))
summary(chomage)
str(chomage)
```

```{r}
commerce_ext <- commerce_ext %>% 
  mutate(OBS_VALUE = as.numeric(OBS_VALUE)) %>% 
  select(-c(DATAFLOW, LAST.UPDATE, freq, geo, OBS_FLAG, CONF_STATUS))
summary(commerce_ext)
str(commerce_ext)
```

```{r}
depense_pub <- depense_pub %>% 
  mutate(OBS_VALUE = as.numeric(OBS_VALUE)) %>% 
  select(-c(DATAFLOW, LAST.UPDATE, freq, geo, OBS_FLAG, CONF_STATUS))
summary(depense_pub)
str(depense_pub)
```

```{r}
fbcf <- fbcf %>% 
  mutate(OBS_VALUE = as.numeric(OBS_VALUE)) %>% 
  select(-c(STRUCTURE, STRUCTURE_ID, freq, Fréquence..relative.au.temps., 
            geo, Entité.géopolitique..déclarante., OBS_FLAG, CONF_STATUS))
summary(commerce_ext)
str(commerce_ext)
```

