---
title: "Consommation, pouvoir d'achat"
output: html_document
date: "2025-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Chargement des packages
```{r}
library(tidyverse)
library(eurostat)
library(lubridate)
library(janitor)
library(ggthemes)
library(mFilter)
```

# Consiommation des ménages

Importation des données
```{r}
conso <- get_eurostat("namq_10_gdp", time_format = "date")
conso <- conso %>%
  filter(
    geo == "PT",
    na_item == "P31_S14_S15",            # consommation des ménages
    s_adj == "SCA",
    unit == "CLV20_MEUR",
    TIME_PERIOD >= as.Date("2023-01-01")
  ) %>%
  arrange(TIME_PERIOD)

conso <- conso %>%
  mutate(
    t_t = (values / lag(values) - 1) * 100,
    yoy = (values / lag(values, 4) - 1) * 100
  ) %>% 
  filter(TIME_PERIOD >= as.Date("2024-01-01"))
```

Graphique
```{r}
ggplot(conso, aes(TIME_PERIOD, values)) +
  geom_line(size = 1.1, color = "darkblue") +
  labs(
    title = "Portugal – Consommation des ménages (volume)",
    subtitle = "En millions d’euros constants – désaisonnalisé (SCA)",
    y = "",
    x = "",
    caption = "Source : Eurostat (nama_10_gdp)"
  ) +
  theme_minimal(base_size = 13)
```

# Confiance des consommateurs

```{r}
confiance_menages <- get_eurostat("ei_bsco_m", time_format = "date") 
confiance_menages <- confiance_menages %>%
  filter(
    geo == "PT",
    indic == "BS-CSMCI",
    unit == "BAL",
    s_adj == "SA",
    TIME_PERIOD >= as.Date("2023-01-01")
  ) %>% 
  arrange(TIME_PERIOD)
```

Graphique
```{r}
ggplot(confiance_menages, aes(TIME_PERIOD, values)) +
  geom_line(size = 1.1, color = "darkorange3") +
  labs(
    title = "Portugal – Indicateur de confiance des consommateurs",
    y = "Solde d’opinion",
    x = "",
    caption = "Source : Eurostat (ei_bsco_m)"
  ) +
  theme_minimal(base_size = 13)
```


